const SESSION_ID = "SADIYA-MD=zoZACSQR#CXFPxMW01m62RQGE8yaV_QMqD3D4bx8p0ppgB_8nbfQ"
const GITHUB_USER_NAME = "Shamalka-deve"
const GITHUB_AUTH_TOKEN = "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"
const DATABASE_REPO_NAME = "SADIYA-MD-DATABASE"

module.exports = {SESSION_ID,GITHUB_USER_NAME,GITHUB_AUTH_TOKEN,DATABASE_REPO_NAME}
